export const MENU_CATEGORIES = [
    "Nigiri",
    "Sashimi",
    "Rolls",
    "Handrolls",
    "Specials",
];

export const MENU_DATA = [
    {
        category: "Nigiri",
        name: "Sake",
        description: "Wild King Salmon, aged 24 hours. Torched with house-made tare.",
        price: "8",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/b34b4c852_generated_e7f8a81c.png",
    },
    {
        category: "Nigiri",
        name: "Maguro",
        description: "Lean bluefin tuna. Clean, mineral finish with a whisper of wasabi.",
        price: "14",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/bfd98dfab_generated_f9891c09.png",
    },
    {
        category: "Nigiri",
        name: "Uni",
        description: "Hokkaido Murasaki. Briny, sweet, with a custard-like finish.",
        price: "18",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/bce10d114_generated_fd901bd3.png",
    },
    {
        category: "Nigiri",
        name: "Hamachi",
        description: "Japanese yellowtail. Buttery, rich, with a clean finish.",
        price: "10",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/bce10d114_generated_fd901bd3.png",
    },
    {
        category: "Nigiri",
        name: "Ebi",
        description: "Cooked tiger shrimp. Sweet and tender with a subtle brine.",
        price: "7",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/b34b4c852_generated_e7f8a81c.png",
    },
    {
        category: "Nigiri",
        name: "Unagi",
        description: "Freshwater eel glazed with kabayaki sauce. Rich and smoky.",
        price: "9",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/bfd98dfab_generated_f9891c09.png",
    },
    {
        category: "Nigiri",
        name: "Aburi Salmon",
        description: "(2pcs) Seared salmon nigiri glazed over house sauce.",
        price: "8.50",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/94034c906_generated_b72e7551.png",
    },
    {
        category: "Nigiri",
        name: "Wagyu Nigiri",
        description: "(2pcs) Seared A5 wagyu beef glazed over house sauce, topped with ginger and green onion.",
        price: "17.95",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/94034c906_generated_b72e7551.png",
    },
    {
        category: "Appetizer",
        name: "Hamachi Kama",
        description: "Hamachi Kama appetizer.",
        price: "MKT",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/94034c906_generated_b72e7551.png",
    },
    {
        category: "Rolls",
        name: "Rainbow Roll",
        description: "California roll base topped with rotating slices of fresh tuna, salmon, yellowtail and avocado.",
        price: "19.14",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/4b7e0c0be_generated_image.png",
    },
    {
        category: "Rolls",
        name: "Dragon Roll",
        description: "Shrimp tempura, cucumber, topped with avocado and unagi sauce.",
        price: "18",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/4b7e0c0be_generated_image.png",
    },
    {
        category: "Rolls",
        name: "Spicy Tuna Roll",
        description: "Bluefin tuna, spicy mayo, cucumber. Finished with togarashi.",
        price: "14",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/4b7e0c0be_generated_image.png",
    },
    {
        category: "Handrolls",
        name: "Negitoro",
        description: "Minced fatty tuna with scallion, wrapped in crisp Ariake nori.",
        price: "12",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/4361a71e6_generated_97b3ba6e.png",
    },
    {
        category: "Handrolls",
        name: "Salmon Skin",
        description: "Crispy salmon skin, cucumber, and scallion in toasted nori.",
        price: "8",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/4361a71e6_generated_97b3ba6e.png",
    },
    {
        category: "Handrolls",
        name: "Spicy Crab",
        description: "Snow crab, spicy mayo, cucumber. Wrapped in crisp nori.",
        price: "10",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/4361a71e6_generated_97b3ba6e.png",
    },
    {
        category: "Specials",
        name: "Sushi Bento Box",
        description: "Assorted nigiri, maki roll, miso soup, and house salad.",
        price: "30.95",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/94034c906_generated_b72e7551.png",
    },
    {
        category: "Specials",
        name: "Regular Sushi",
        description: "Chef's selection of eight pieces of nigiri with a California roll.",
        price: "28.95",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/b34b4c852_generated_e7f8a81c.png",
    },
    {
        category: "Specials",
        name: "Combo Sushi",
        description: "Ten pieces of nigiri, a specialty roll, and miso soup.",
        price: "32.95",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/bfd98dfab_generated_f9891c09.png",
    },
    {
        category: "Specials",
        name: "Sushi & Sashimi",
        description: "Five pieces of nigiri, nine pieces of sashimi, and a California roll.",
        price: "35.95",
        image: "https://media.base44.com/images/public/69c4afc75d0284fc64e49e47/94034c906_generated_b72e7551.png",
    },
];
